{
    "name": "Tynor Shopify Inbound Bridge",
    "summary": "Connector-independent inbound order payment bridge for Shopify-fed orders.",
    "version": "saas~19.2.1.0",
    "category": "Accounting/Accounting",
    "author": "Tynor",
    "license": "LGPL-3",
    "depends": ["sale_management", "account", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/payment_method_map_data.xml",
        "data/cron.xml",
        "data/mail_layout.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/payment_method_map_views.xml",
    ],
    "installable": True,
    "application": False,
}
