from . import res_partner
from . import res_config_settings
from . import crm_lead
from . import sale_order
from . import account_move
from . import product_tag
from . import tynor_ndis_order
from . import product_retail_price
from . import product_size_chart
