{
    "name": "Tynor Website Custom",
    "summary": "Website, B2B, pricing, branding, and NDIS customizations for Tynor AHS",
    "version": "saas~19.2.1.0",
    "category": "Website",
    "author": "Tynor",
    "license": "LGPL-3",
    "depends": [
        "tynor_b2b_wholesale",
        "tynor_wholesale_management",
        "tynor_shopify_inbound_bridge",
        "tynor_sale_report_custom",
        "website_sale",
        "sale_management",
        "account",
        "portal",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ndis_sequence.xml",
        "data/ndis_email_template.xml",
        "data/cron_auto_invoice.xml",
        "data/remove_odoo_tag.xml",
        "views/website_category_tiles.xml",
        "views/website_sale_price_hide.xml",
        "views/website_sale_size_chart.xml",
        "views/website_sale_checkout.xml",
        "views/website_product_desc.xml",
        "views/wholesale_notification.xml",
        "views/remove_odoo_branding.xml",
        "views/ndis_form_website.xml",
        "views/ndis_backend_views.xml",
        "views/product_size_chart_views.xml",
        "views/res_config_settings_view.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "tynor_website_custom/static/src/css/category_tiles.css",
            "tynor_website_custom/static/src/css/website_custom.css",
            "tynor_website_custom/static/src/js/category_nav.js",
            "tynor_website_custom/static/src/js/ndis_form.js",
            "tynor_website_custom/static/src/js/wholesale_banner.js",
            "tynor_website_custom/static/src/js/website_size_bulk_order.js",
        ],
    },
    "installable": True,
    "application": False,
}
